// ── SQLite depolama katmanı: dış API ──
// Uygulama tek `require("./db.cjs")` görür; işlevler electron/db/ altındaki modüllerden gelir (refactor §3.1, 08.09.2026):
//   baglanti (bağlantı, anahtar, yollar) · sema (şema/göç/tohum) · meta · kullanicilar · gruplar · oyuncular · mesaj ·
//   belgeler · aidat · makbuz · antrenman · sezon · pano · lisansDurum · yedek
// Renderer bu modülü hiç görmez; ipc/data.cjs (beyaz liste: yetki.cjs) üzerinden çağrılır.
const m = {
  ...require("./db/baglanti.cjs"),
  ...require("./db/meta.cjs"),
  ...require("./db/kullanicilar.cjs"),
  ...require("./db/sema.cjs"),
  ...require("./db/aidat.cjs"),
  ...require("./db/antrenman.cjs"),
  ...require("./db/gruplar.cjs"),
  ...require("./db/oyuncular.cjs"),
  ...require("./db/mesaj.cjs"),
  ...require("./db/belgeler.cjs"),
  ...require("./db/makbuz.cjs"),
  ...require("./db/sezon.cjs"),
  ...require("./db/pano.cjs"),
  ...require("./db/lisansDurum.cjs"),
  ...require("./db/yedek.cjs"),
};

module.exports = {
  islem: m.islem,
  init: m.init,
  close: m.close,
  checkpoint: m.checkpoint,
  isEncrypted: m.isEncrypted,
  getDbKey: m.getDbKey,
  getUploadsDir: m.getUploadsDir,
  getDbPath: m.getDbPath,
  yedekBilgisi: m.yedekBilgisi,
  yedekBilgisiBuffer: m.yedekBilgisiBuffer,
  duzKopyaOlustur: m.duzKopyaOlustur,
  duzVeritabaniniSifrele: m.duzVeritabaniniSifrele,
  hamBaglanti: m.hamBaglanti,
  getMetaValue: m.getMetaValue,
  setMetaValue: m.setMetaValue,
  getSetting: m.getSetting,
  setSetting: m.setSetting,
  aidatAyarlari: m.aidatAyarlari,
  aidatAyarlariKaydet: m.aidatAyarlariKaydet,
  sezonAdayListesi: m.sezonAdayListesi,
  sezonDurumu: m.sezonDurumu,
  sezonTarihleri: m.sezonTarihleri,
  sezonTarihKaydet: m.sezonTarihKaydet,
  sezonListesiTarihli: m.sezonListesiTarihli,
  sezonListesi: m.sezonListesi,
  yeniSezonaGec: m.yeniSezonaGec,
  SEZON_DURUMLARI: m.SEZON_DURUMLARI,
  getUserByUsername: m.getUserByUsername,
  createUser: m.createUser,
  verifyPassword: m.verifyPassword,
  changePassword: m.changePassword,
  listAgeGroups: m.listAgeGroups,
  createAgeGroup: m.createAgeGroup,
  updateAgeGroup: m.updateAgeGroup,
  haftayiProgramdanDoldur: m.haftayiProgramdanDoldur,
  createPlayer: m.createPlayer,
  updatePlayer: m.updatePlayer,
  getPlayer: m.getPlayer,
  listPlayers: m.listPlayers,
  deletePlayer: m.deletePlayer,
  oyuncuKisiselVeriSil: m.oyuncuKisiselVeriSil, // db:call beyaz listesinde DEĞİL: dosya silme ile birlikte files:oyuncuKisiselVeriSil
  listGuardians: m.listGuardians,
  addGuardian: m.addGuardian,
  updateGuardian: m.updateGuardian,
  deleteGuardian: m.deleteGuardian,
  listEmergency: m.listEmergency,
  addEmergency: m.addEmergency,
  deleteEmergency: m.deleteEmergency,
  mesajKaydet: m.mesajKaydet,
  mesajSil: m.mesajSil,
  sonMesajlar: m.sonMesajlar,
  antrenmanVelileri: m.antrenmanVelileri,
  updateTraining: m.updateTraining,
  bildirimGerekliAyarla: m.bildirimGerekliAyarla,
  grupBildirimKaydet: m.grupBildirimKaydet,
  grupBildirimSil: m.grupBildirimSil,
  listDocuments: m.listDocuments,
  addDocument: m.addDocument,
  belgeEkle: m.belgeEkle,
  tekilBelgeMi: m.tekilBelgeMi,
  deleteDocument: m.deleteDocument,
  updateDocument: m.updateDocument,
  getDocument: m.getDocument,
  saglikRaporuDurumu: m.saglikRaporuDurumu,
  saglikRaporuListesi: m.saglikRaporuListesi,
  listFeeItems: m.listFeeItems,
  updateFeeItem: m.updateFeeItem,
  listFeeTypes: m.listFeeTypes,
  ensureMonthlyDues: m.ensureMonthlyDues,
  ensureMonthlyDuesAraligi: m.ensureMonthlyDuesAraligi,
  getDue: m.getDue,
  listDues: m.listDues,
  listUnpaid: m.listUnpaid,
  listUnpaidSezon: m.listUnpaidSezon,
  listUnpaidAralik: m.listUnpaidAralik,
  sezonAidatOzeti: m.sezonAidatOzeti,
  aidatOzeti: m.aidatOzeti,
  createReceipt: m.createReceipt,
  getReceipt: m.getReceipt,
  listReceipts: m.listReceipts,
  listReceiptsByDate: m.listReceiptsByDate,
  listCancelledReceipts: m.listCancelledReceipts,
  setReceiptPdf: m.setReceiptPdf,
  createTraining: m.createTraining,
  listTrainings: m.listTrainings,
  trainingCalendar: m.trainingCalendar,
  cancelTraining: m.cancelTraining,
  setAttendance: m.setAttendance,
  listAttendance: m.listAttendance,
  playerAttendance: m.playerAttendance,
  playerAttendanceSon: m.playerAttendanceSon,
  deleteAgeGroup: m.deleteAgeGroup,
  listPlayersWithDue: m.listPlayersWithDue,
  playersPage: m.playersPage,
  panoOzet: m.panoOzet,
  cancelReceipt: m.cancelReceipt,
  attendanceSummary: m.attendanceSummary,
  attendanceReport: m.attendanceReport,
  listUsers: m.listUsers,
  setUserActive: m.setUserActive,
  resetUserPassword: m.resetUserPassword,
  deleteUser: m.deleteUser,
  kurtarmaKodlariUret: m.kurtarmaKodlariUret,
  kurtarmaKoduSayisi: m.kurtarmaKoduSayisi,
  kurtarmaIleSifirla: m.kurtarmaIleSifirla,
  kurtarmaKoduNormalize: m.kurtarmaKoduNormalize,
  lisansDurumu: m.lisansDurumu,
  lisansKaydet: m.lisansKaydet,
  leaseKaydet: m.leaseKaydet,
  lisansAktiflestir: m.lisansAktiflestir,
  lisansYenile: m.lisansYenile,
  lisansSaltOkunurMu: m.lisansSaltOkunurMu,
};
